

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

networks:
  frontend-network:
    driver: bridge
